import type { Metadata } from 'next'
import Link from 'next/link'

// T01-LEGAL-COUNSEL-PACK: Standalone sharia disclaimer page for ChatIslam
// Cross-ref: CONTMOD T07 (per-response disclaimer already in MessageBubble + DisclaimerFooter)
// DO NOT publish without counsel review (U-15 gate).
// LAST_UPDATED: 2026-05-16

export const metadata: Metadata = {
  title: 'AI Islamic Guidance Disclaimer — ChatIslam',
  description:
    'Important notice about the nature of AI-generated Islamic guidance on ChatIslam. Not a fatwa. Not a substitute for a qualified scholar.',
  robots: { index: false }, // U-15: unpublished until counsel review
}

export default function ShariaDisclaimerPage() {
  return (
    <main className="min-h-screen" id="main-content">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">

        {/* Draft gate */}
        <div className="mb-8 rounded-lg border border-yellow-500/40 bg-yellow-500/10 px-4 py-3 text-sm text-yellow-300">
          <strong>DRAFT — Not yet effective.</strong> Counsel review pending (U-15). Committed for development only. Do not link from production footers until U-15 is resolved.
        </div>

        <Link href="/legal" className="mb-8 inline-block text-sm opacity-60 hover:opacity-90 transition-opacity">
          &larr; Legal
        </Link>

        <h1 className="mt-4 text-3xl font-bold sm:text-4xl">
          AI Guidance Disclaimer
        </h1>
        <p className="mt-3 mb-10 text-sm opacity-50">
          Effective date: pending counsel review — ChatIslam, operated by Ummeco, LLC
        </p>

        <div className="space-y-10 leading-relaxed text-sm opacity-80">

          <section className="rounded-xl border border-red-500/30 bg-red-500/10 px-6 py-6">
            <h2 className="text-base font-semibold text-red-300 mb-2">This is not a fatwa.</h2>
            <p className="text-sm text-red-200/80">
              Every response generated by ChatIslam is AI-generated for informational purposes
              only. It is not a fatwa, a legal opinion under Islamic law, or an authoritative
              religious ruling. It does not substitute for the guidance of a qualified Islamic
              scholar.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">1. Nature of AI Responses</h2>
            <p className="mb-4">
              ChatIslam uses large language model (LLM) technology to provide information about
              Islam. The system draws on texts from the Quran, the Sunnah, and classical Islamic
              scholarship to construct responses. However, LLMs can make errors, misattribute
              sources, generate plausible-sounding but incorrect religious information, and may
              not account for your specific personal circumstance, madhab, or local scholarly
              consensus.
            </p>
            <p>
              No AI system is capable of performing ijtihad or issuing a binding fatwa. That
              authority rests exclusively with qualified scholars who have received proper
              ijazah in Islamic jurisprudence.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Scholarly Guidance is Required for Personal Matters</h2>
            <p className="mb-4">
              For personal religious decisions — including but not limited to matters of halal
              and haram, marriage and divorce, business transactions, prayer obligations, and
              zakah calculation — you must consult a qualified Islamic scholar. ChatIslam
              provides general educational information only.
            </p>
            <p>
              Reliance on AI-generated responses for personal fiqh decisions is not
              recommended and is done entirely at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. Our Theological Baseline</h2>
            <p className="mb-4">
              ChatIslam is designed with Ahl us-Sunnah wal-Jamaah guidelines. Responses favor
              positions within the four accepted madhabs (Hanbali, Shafi&apos;i, Maliki, Hanafi)
              and Athari aqeedah as primary, with Ash&apos;ari and Maturidi positions
              acknowledged as within Ahl us-Sunnah.
            </p>
            <p>
              This does not mean all responses are correct. Even within Sunni scholarship,
              there is legitimate ikhtilaf (scholarly disagreement). ChatIslam may present
              one view without fully representing the range of scholarly opinions. Verification
              with a scholar who knows your circumstances is always the correct path.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. How We Flag Religious Information</h2>
            <p className="mb-4">
              Each AI response in ChatIslam is accompanied by a disclaimer: &quot;AI-generated
              for informational purposes only. Not a fatwa or religious ruling. Consult a
              qualified Islamic scholar for personal guidance.&quot; This notice appears on every
              response and in the chat interface.
            </p>
            <p>
              Where citations are provided, they reference the source text (e.g., a hadith
              collection, a fiqh text, or a Quranic ayah). Citations help you verify the
              information independently. They do not constitute a scholarly opinion or ruling.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Human Escalation</h2>
            <p>
              ChatIslam routes complex fiqh questions — those involving individual circumstances,
              nuanced legal matters, or sensitive personal situations — to a scholar escalation
              flow rather than generating an AI response. This is an intentional design choice.
              When the system escalates, that is the system working correctly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. No Liability</h2>
            <p>
              Ummeco, LLC provides ChatIslam on an &quot;as is&quot; basis. To the fullest extent
              permitted by law, we disclaim all liability for any decisions made in reliance on
              AI-generated content from ChatIslam. See our{' '}
              <Link href="/terms" className="text-[#5A9438] hover:underline">
                Terms of Service
              </Link>{' '}
              for the full limitation of liability.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Contact</h2>
            <p>
              Questions about this disclaimer:{' '}
              <a href="mailto:legal@ummat.dev" className="text-[#5A9438] hover:underline">
                legal@ummat.dev
              </a>
            </p>
          </section>

          <section className="border-t border-white/10 pt-6">
            <h2 className="text-lg font-semibold mb-3">Related</h2>
            <ul className="space-y-1">
              <li><Link href="/terms" className="text-[#5A9438] hover:underline">Terms of Service</Link></li>
              <li><Link href="/privacy" className="text-[#5A9438] hover:underline">Privacy Policy</Link></li>
              <li><Link href="/legal/california" className="text-[#5A9438] hover:underline">California Privacy Rights</Link></li>
            </ul>
          </section>

        </div>
      </div>
    </main>
  )
}
