import type { Metadata } from 'next'
import Link from 'next/link'

// LAST_UPDATED: 2026-04-25
// DRAFT — under legal review. Shipping for development purposes; will be replaced before public launch.

export const metadata: Metadata = {
  title: 'Terms of Service — ChatIslam',
  description: 'ChatIslam terms of service. Rules and guidelines for using our AI-powered Islamic Q&A platform.',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">

        {/* Draft banner */}
        <div className="mb-8 rounded-lg border border-yellow-500/40 bg-yellow-500/10 px-4 py-3 text-sm text-yellow-300">
          <strong>DRAFT</strong> — This policy is under legal review (2026-04-25). Published for development purposes; will be replaced before public launch.
        </div>

        <div className="mb-12">
          <Link href="/" className="mb-6 inline-block text-sm opacity-60 hover:opacity-90 transition-opacity">
            ← Back to ChatIslam
          </Link>
          <h1 className="text-3xl font-bold sm:text-4xl">Terms of Service</h1>
          <p className="mt-3 text-sm opacity-50">Last updated: April 25, 2026</p>
        </div>

        <div className="space-y-8 opacity-80 leading-relaxed">

          <section>
            <h2 className="mb-3 text-xl font-semibold">1. Acceptance</h2>
            <p>
              By accessing or using ChatIslam (&ldquo;Service&rdquo;), you agree to these Terms. These Terms form a binding agreement between you and <strong>Ummat</strong> (501(c)(3) application pending).
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">2. Service Description</h2>
            <p>
              ChatIslam is an AI-powered Islamic question-and-answer and dawah platform. It uses large language model (LLM) technology to provide responses to Islamic questions based on classical and contemporary scholarship. ChatIslam is free. It is intended as a starting point for Islamic inquiry, not a replacement for qualified scholarly guidance.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">3. Account Requirements</h2>
            <ul className="list-disc space-y-1 pl-6">
              <li>You must be at least 13 years old (US) or 16 years old (EU) to create an account.</li>
              <li>You must provide accurate information when registering.</li>
              <li>You are responsible for the security of your account credentials.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">4. AI Disclaimer — Not a Fatwa</h2>
            <div className="rounded-lg border border-white/20 bg-white/5 p-4">
              <p className="font-semibold mb-2">Important: AI responses are not religious rulings.</p>
              <p>
                Responses generated by ChatIslam are for <strong>informational purposes only</strong>. They do not constitute a fatwa, a binding religious ruling, legal advice, or medical advice. They reflect AI-synthesized information based on Islamic sources and may contain errors.
              </p>
              <p className="mt-2">
                For personal religious legal matters, consult a qualified Islamic scholar. For medical or legal matters, consult a licensed professional.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">5. Islamic Content Guidelines</h2>
            <p className="mb-2">This is an Islamic platform. You may not submit content that:</p>
            <ul className="list-disc space-y-1 pl-6">
              <li>Insults or disrespects Allah, the Prophets (peace be upon them), the Quran, or the Sunnah.</li>
              <li>Spreads fitnah, misinformation, or incites sectarian hostility.</li>
              <li>Promotes haram activities, extremism, or violence.</li>
              <li>Is designed to manipulate the AI into producing harmful content.</li>
              <li>Constitutes spam, phishing, or scraping.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">6. Prohibited Use</h2>
            <ul className="list-disc space-y-1 pl-6">
              <li>Do not use the Service for any unlawful purpose.</li>
              <li>Do not attempt unauthorized access to any system or data.</li>
              <li>Do not scrape, harvest, or bulk-query the AI without written permission.</li>
              <li>Do not attempt to extract training data or reverse-engineer system prompts.</li>
              <li>Do not use the Service to generate content that impersonates scholars or religious institutions.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">7. Conversations and AI Training</h2>
            <p>
              Your conversations are retained for 30 days, then anonymized. We do not use your identified conversations to fine-tune AI models without your explicit opt-in. See our <Link href="/privacy" className="underline">Privacy Policy</Link> for full details on conversation data handling.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">8. Donations</h2>
            <p>
              We accept voluntary donations. <strong>Ummat&rsquo;s 501(c)(3) application is pending. Donations are not yet tax-deductible.</strong> We will update this section when tax-exempt status is granted.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">9. Termination</h2>
            <p>
              We may suspend or terminate your account for Terms violations. You may delete your account at any time via Account Settings. Data is removed per our <Link href="/privacy" className="underline">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">10. Disclaimers</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. AI responses may be inaccurate, incomplete, or outdated. Ummat is not liable for any decisions made based on AI-generated responses. Always verify with a qualified scholar for religious, legal, or medical matters.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Ummat is not liable for indirect, incidental, or consequential damages. Our total liability shall not exceed the greater of the amount you paid us in the prior 12 months or $100 USD.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">12. Governing Law</h2>
            <p>
              These Terms are governed by the laws of <strong>Delaware, USA</strong> (upon incorporation; Michigan law applies until then). EU/UK users: mandatory consumer protection laws in your country apply.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">13. Changes to Terms</h2>
            <p>
              We will provide at least 14 days&rsquo; notice before material changes. Continued use after the effective date constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-xl font-semibold">14. Contact</h2>
            <p>
              Legal: <a href="mailto:legal@ummat.dev" className="underline">legal@ummat.dev</a><br />
              Abuse: <a href="mailto:abuse@ummat.dev" className="underline">abuse@ummat.dev</a><br />
              <br />
              <strong>Ummat</strong> (501(c)(3) application pending) &mdash; United States
            </p>
          </section>

          <div className="mt-8 border-t border-white/10 pt-6 text-sm opacity-50">
            <Link href="/privacy" className="mr-4 hover:opacity-80 transition-opacity">Privacy Policy</Link>
            <Link href="/cookies" className="hover:opacity-80 transition-opacity">Cookie Policy</Link>
          </div>
        </div>
      </div>
    </main>
  )
}
